### ISSUE TITLE
The alien function "sysconf" is undefined

### ISSUE THREAD

**Issue by sreerampeela** [santosardr/genppi#1]
Hi, I have been trying to use genppi to generate PPI networks for the test files. I am using windows 11, and downloaded the binaries from the website (32 gb memory and speed optimization). However, I am getting the following error:

The alien function "sysconf" is undefined.  Below is the full output of running the command with test genomes in the directory test_genomes:

GENPPI VERSION: 1.1
RELEASE NUMBER: 55e436b354ba1f3575529aaccc51002e7bf68ee6
REPOSITORY: https://github.com/santosardr/genppi

Directory parameter:
-dir <workingdir> = .\test_genomes

Parameters of ppi by conserved neighbourhood:
-cnp <conserved neighbourhood score percentage> = 70%
-expt <type of expansion of the conserved gene neighborhood> = fixed (default)
-w1 <window size 1> = 7
-cw1 <gene conservation required for window 1> = 4 (default)
-w2 <window size 2> = 7 (default)
-cw2 <gene conservation required for window 2> = 3 (default)
-w3 <window size 3> = 5 (default)
-cw3 <gene conservation required for window 3> = 2 (default)
-w4 <window size 4> = 3 (default)
-cw4 <gene conservation required for window 4> = 1 (default)

Parameters of ppi by phylogenetic profile:
Method 2 - PPi prediction by phylogenetic profile without filters
-ppp <phylogenetic profiles score percentage> = 30% (default)
-ppdifftolerated <difference in phylogenetic profiles tolerated to infer ppi> = 1
-pphistofilter <build the phylogenetic profile of genes with a higher percentage of identity>
-ppaadifflimit <amino acid difference limit> = 0 (default)
-ppaacheckminlimit <minimum amount of amino acids to check> = 26 (default)

Amino acid histogram parameters:
-aadifflimit <amino acid difference limit> 1 (default)
-aacheckminlimit <minimum amount of amino acids to check> 25 (default)

Making ppi prediction, please wait.

Generating amino acids histogram;
[05 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100]%
[============================================================]

debugger invoked on a SB-KERNEL::UNDEFINED-ALIEN-FUNCTION-ERROR @21A20831 in thread
#<THREAD "main thread" RUNNING {1001550003}>:
  The alien function "sysconf" is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit from the current thread.

("undefined function")
0]0

Please help me in troubleshooting it.

**Comment by santosardr** [comment]
Dear sreerampeela,
this code has the purpose to read the number of CPUs in a machine. It works fine in the Linux OS. It's a surprise to me that such code does not work in Microsoft Windows. I will code something to work whatever the platform. In the meantime, a possible workaround is simple to comment on this code and make the workers return the number of CPUs in our machine and recompile. 

;(define-alien-routine "sysconf" long (name int))
;(defconstant +_SC_NPROCESSORS_ONLN+ 84)
; Fixing for eight cpus
(defun workers()  8)

If you are not able do to that I can provide a compiled code like that for you.
Regards,
Anderson Santos

**Comment by santosardr** [comment]
Dear @sreerampeela,
Thank you for pointing out the problem. I believe the issue is fixed. I tested in the Linux and Windows OSs. I do not have a Macintosh, so I still depend on a friend of mine to try it on Mac. Even so, I believe the problem is solved for the three platforms. Please, download a new copy of the GENPPI executable or recompile it as you wish. 
Regards,
Anderson Santos
